DJANGO_SECRET_KEY = "django-insecure-6iye#=qcyi493w-))2jnml41q0h@!@+^0golqzc!eqak^@amk&"

GOOGLE_API_KEY = "AIzaSyDfBbc5xI42UiBdk_afAvlU3tKkFHy1pIw"

TWITTER_BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAAGqOjAEAAAAAUgjyUXlCmMk5I6UXfsvPDqh8LvI%3Dd46LDr0WGqiVGWXyavt69gh4RJQoULojOsLlFgm13hS4JFyaq0"
TWITTER_API_KEY_SECRET = "V4SdjFXnMZSYOpav9cs2NmLGSbnM6a1ceKlP0fJZiJiE96vYSu"
TWITTER_API_KEY = "fX3QIEzbEjuQKUmRVJA789CKc"
